// <auto-generated />
namespace App.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addinitialtbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinitialtbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202102231334055_addinitialtbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
